SFA/SFA/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginafiltro.urls'))
]

SFA/homepage/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', get_pagina_login, name ='pagina_login'),
    path('cadastro/', get_pagina_cadastro, name ='pagina_cadastro'),
    path('cadastrar/', cadastrarusuario, name='cadastrar'),
    path('logar/', logarusuario, name='logar')
]

SFA/homepage/models.py
from django.db import models
from django.contrib.auth.models import User

class Usuario(models.Model):
    
    nome = models.CharField(max_length=150, null=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="usuario")

    @property
    def email(self):
        return self.user.email
    
    @property
    def nomeusuario(self):
        return self.user.username

# Create your models here.

SFA/homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

class CadastrarNovoUsuario(forms.Form):

    nome = forms.CharField(required=True)
    usuario = forms.CharField(required=True)
    email = forms.CharField(required=True)
    senha = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        
        if not super(CadastrarNovoUsuario, self).is_valid():
            self.adiciona_erro('Dados incorretos !')
            valid = False
        
        user_exists = User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro("Usuario ja existe")
            valid = False

        return valid

    def adiciona_erro(self, message):
        error = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        error.append(message)


class Logar(forms.Form):
    
    usuario = forms.CharField(required=True)
    senha = forms.CharField(required=True)

    def is_valid(self):
        valid = True

        if not super(Logar, self).is_valid():
            self.adiciona_erro('Dados incorretos')
            valid = False
   
        return valid

    def adiciona_erro(self, message):  
        error = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        error.append(message)

SFA/homepage/views.py
from django.shortcuts import render 
from django.http import HttpResponse
from .forms import CadastrarNovoUsuario, Logar
from .models import Usuario
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


def get_pagina_login(request):
    return render(request, 'home_template_login.html', {})


def get_pagina_cadastro(request):
    return render(request, 'home_template_cadastro.html', {})

def logarusuario(request):
    if request.method == "POST":
        form = Logar(request.POST)
        if form.is_valid():
            dados = form.data
            user = authenticate(username=dados['usuario'], password=dados['senha'])
            if user is not None:
                login(request, user)
                return HttpResponse('O novo usuario esta logado no sistema .')
            else:
                form.adiciona_erro(message='Usuario ou senha esta errado')
                return render(request, 'home_template_login.html', {'form': form})
        else:
            return render(request, 'filtro_template_buscas.html')


def cadastrarusuario(request):
    if request.method == "POST":
        form = CadastrarNovoUsuario(request.POST)
        if form.is_valid():
            dados = form.data
            print(dados['usuario'])
            novo_user = User.objects.create_user(dados['usuario'], dados['email'], dados['senha'])
            novo_usuario = Usuario(nome=dados['nome'], user=novo_user)
            novo_usuario.save()
            return HttpResponse('O cadastro foi feito !')
        else:
            return render(request, 'home_template_login.html', {'form': form})

SFA/homepage/templates/home_template_cadastro.html
{% extends 'home_template_main.html' %}

{% block body %}

<div class="cadastro_page container">
    <div class="jumbotron">
        <h1>Cadastro</h1>

        <form action="{% url 'cadastrar' %}" method="POST" class="needs-validation">
            {% csrf_token %}

            {% if form.errors %}
            <div class="alert alert-danger" style="padding-top:50px;">
                <button type="button" class="close"> &times; </button>
                {{ form.non_field_errors }}
            </div>
            {% endif%}

            <div class="form-group">
                <label for="id_nome">Nome Completo</label>
                <input type="text" class="form-control" id="id_nome" name="nome" placeholder="Digite o nome completo"
                    required>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_usuario">Nome de usuário</label>
                    <input type="text" class="form-control" id="id_usuario" name="usuario"
                        placeholder="Digite seu email" required>
                </div>
                <div class="form-group col-md-6">

                    <label for="id_senha">Senha</label>
                    <input type="password" class="form-control" id="id_senha" name="senha"
                        placeholder="Digite sua senha" required>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_email">E-mail</label>
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Digite seu e-mail"
                        required>
                </div>
                
            </div>
            <button type="submit" class="btn btn-primary">Registrar</button>
        </form>
    </div>

</div>

<style>
    .cadastro_page {
        padding-top: 11%;
    }
</style>
{% endblock %}

SFA/homepage/templates/home_template_login.html
{% extends 'home_template_main.html' %}

{% block body %}

<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center text-white mb-4">Bootstrap 4 Login Form</h2>
            <div class="row">
                <div class="col-md-6 mx-auto">

                    <!-- form card login -->
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">Login</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'logar' %}" class="form" role="form" autocomplete="off" id="formLogin" novalidate=""
                                method="POST">
                                {% csrf_token %}

                                {% if form.errors %}
                                <div class="alert alert-danger" style=" ">
                                    {{ form.non_field_errors }}
                                </div>
                                {% endif%}

                                <div class="form-group">

                                    <label for="uname1">Email:</label>
                                    <input type="text" class="form-control form-control-lg rounded-0" name="usuario"
                                        id="usuario" required="">
                                    <div class="invalid-feedback">Preencha seu email.</div>

                                </div>
                                <div class="form-group">

                                    <label>Senha: </label>
                                    <input type="password" class="form-control form-control-lg rounded-0" id="id_senha"
                                        required="" autocomplete="new-password" name='senha'>
                                    <div class="invalid-feedback">Coloque sua senha !</div>

                                </div>
                                <div>

                                    <a href="{% url 'pagina_cadastro' %}" class="text-dark">cadastre-se </a>

                                </div>
                                <button type="submit" class="btn btn-primary btn-lg float-right"
                                    id="btnLogin">Entrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
{% endblock %}

SFA/homepage/templates/home_template_main.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="João Vitor, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Sistema de Filtragem de Ações</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 988px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            font-size: .875rem;
        }

        .feather {
            width: 16px;
            height: 16px;
            vertical-align: text-bottom;
        }

        /*
 * Sidebar
 */

        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            z-index: 100;
            /* Behind the navbar*/
            padding: 48px 0 0;
            /* Height of navbar */
            box-shadow: inset -1px 0 0 rgba(8, 55, 123);
        }

        .sidebar-sticky {
            position: relative;
            top: 0;
            height: calc(100vh - 48px);
            padding-top: .5rem;
            overflow-x: hidden;
            overflow-y: auto;
            /* Scrollable contents if viewport is shorter than content. */
        }

        @supports ((position: -webkit-sticky) or (position: sticky)) {
            .sidebar-sticky {
                position: -webkit-sticky;
                position: sticky;
            }
        }

        .sidebar .nav-link {
            font-weight: 500;
            color: #333;
        }

        .range_dados {
            width: 70%;
        }

        .sidebar .nav-link .feather {
            margin-right: 4px;
            color: #999;
        }

        .sidebar .nav-link.active {
            color: #007bff;
        }

        .sidebar .nav-link:hover .feather,
        .sidebar .nav-link.active .feather {
            color: inherit;
        }

        .sidebar-heading {
            font-size: .75rem;
            text-transform: uppercase;
        }

        /*


        /*
 * Content
 */

        [role="main"] {
            padding-top: 190px;
            /* Space for fixed navbar */
        }

        @media (min-width: 988px) {
            [role="main"] {
                padding-top: 48px;
                /* Space for fixed navbar */
            }
        }

        /*
 * Navbar
 */

        .navbar-brand {
            padding-top: .75rem;
            padding-bottom: .75rem;
            font-size: 1rem;
            background-color: rgba(8, 55, 123);
            box-shadow: inset -1px 0 0 rgba(8, 55, 123);
        }

        .navbar .form-control {
            padding: .75rem 1rem;
            border-width: 0;
            border-radius: 0;
        }

        .form-control-dark {
            color: #08377b;
            background-color: rgba(8, 55, 123);
            border-color: rgba(8, 55, 123);
        }

        .form-control-dark:focus {
            border-color: transparent;
            box-shadow: 0 0 0 3px rgba(8, 55, 123 .25);
        }
    </style>
    <!-- Custom styles for this template -->
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #08377b;">
             {% load static from staticfiles %}
            <img src="{% static 'img/SFABlue.png' %}" style="width:6%">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">SOBRE O SFA<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                  <a class="nav-link"  href="{% url 'pagina_cadastro' %}" > CADASTRAR <span class="sr-only">(current)</span></a>
                </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'pagina_login' %}" >LOGAR</a>
              </li>
            </ul>
          </div>
        </nav>
      </header>



    {% block body %} {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>